site_name: Sistemas Hardware-Software - 2024/1
site_author: Igor Montagner, Maciel Calebe Vidal, Fabio Lubacheski


extra:
    materia: Sistemas Hardware-Software
    professor: Fabio Lubacheski
    semestre: 2024/1

theme:
  feature:
    tabs: true
  name: active-handout
  palette:
    scheme: preference
    primary: brown
    accent: amber

docs_dir: material
site_dir: docs

repo_url: https://github.com/Insper/SistemasHardwareSoftware/
repo_name: "sistemashardwaresoftware"
site_url: https://insper.github.io/SistemasHardwareSoftware/

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/insper-education/active-handout-plugins-js@main/package/plugin-bundle.js
    #  - http://localhost:9000/plugin-bundle.js
  - js/termynal.js
  - js/custom.js

extra:
  ihandout_config:
#    counter:
#      - question
#      - tip
#      - exercise
#      - example
    report:
      api-base: https://devlife.insper-comp.com.br/api/offerings/1/
      url: https://devlife.insper-comp.com.br/api/offerings/1/exercises/

# Extensions / plugins
plugins:
  - git-revision-date-localized
  - search

extra_css:
    - css/termynal.css

markdown_extensions:
  - markdown.extensions.tables
  - tables
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: code
      check_paths: true

nav:
    - Home: index.md
    - Entregas e Prazos: sobre.md

    - Aulas:
        - aulas/01-inteiros/index.md
        - aulas/02-ram/index.md
        - aulas/03-arquitetura-x86/index.md
        - aulas/04-funcoes-mov/index.md
        - aulas/05-condicionais/index.md
        - aulas/06-condicionais-funcoes/index.md  
        - aulas/07-loops/index.md
        - aulas/08-variaveis-locais/index.md
        - aulas/09-arrays/index.md
        - aulas/10-malloc/index.md
        #- aulas/11-tipos-de-dados/index.md
        #- aulas/12-revisao/index.md
        ##- aulas/13-linux-do-zero/index.md
        #- aulas/13-processos/index.md
        #- aulas/14-exec/index.md
        #- aulas/15-entrada-saida/index.md
        #- aulas/16-sinais-I/index.md
        #- aulas/17-sinais-II/index.md
        #- aulas/18-threads-I/index.md
        #- aulas/19-sincronizacao/index.md
        #- aulas/20-semaforos/index.md
        #- aulas/21-semaforos-II/index.md
        #- aulas/22-questoes-de-revisao/index.md
    - Labs:
        - labs/hackerlab.md
        #- labs/processos.md
        #- labs/threads.md
    - Dicas:
        - outros/github.md
        - outros/vbox.md
        - outros/DicasLinks.md

